import Config

# Configure your database
config :contact360, Contact360.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "contact360_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :contact360, Contact360Web.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "wgC50s00P8DXaovAafDjSvzRpgD4N5OUXYpaJ24k+TWIafIz4xKQhL8+x4Cvx+OG",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:contact360, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:contact360, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :contact360, Contact360Web.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/contact360_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :contact360, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Enable the fake API, which involves two changes: base url for the bexio client and the faker API
config :contact360, :bexio_api_faker, true
config :bexio_api_client, :req_options, base_url: "http://localhost:4000/bexio-faker/api/"
config :bexio_api_client, :idp_url, "http://localhost:4000/bexio-faker/idp/"

# should have an ueberauth for local work without any need to login at all, only active in dev...
config :ueberauth, Ueberauth,
  providers: [
    # default scopes are very low, only the sync user needs more access and that will be asked separately
    # during the registration process
    bexio: {Ueberauth.Strategy.Bexio, [default_scope: "openid email profile"]},
    faker: {Contact360Web.BexioFaker.Strategy.FakeLogin, []}
  ]
